/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.3.4).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.merann.bopopov.autoshowroom.server.rs.api;

import ru.merann.bopopov.autoshowroom.server.model.ResultListOrder;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-04-10T11:51:56.409+03:00[Europe/Moscow]")

@Validated
@Api(value = "orders", description = "the orders API")
public interface OrdersApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    @ApiOperation(value = "", nickname = "getAllOrders", notes = "Get all orders information", response = ResultListOrder.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successfully get orders", response = ResultListOrder.class) })
    @RequestMapping(value = "/orders",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<ResultListOrder> getAllOrders() {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    ApiUtil.setExampleResponse(request, "application/json", "{  \"items\" : [ {    \"car\" : {      \"options\" : [ {        \"price\" : 65000,        \"name\" : \"Спортивный аэродинамический обвес\",        \"id\" : 3      }, {        \"price\" : 65000,        \"name\" : \"Спортивный аэродинамический обвес\",        \"id\" : 3      } ],      \"model\" : {        \"price\" : 6000000,        \"name\" : \"A8\",        \"id\" : 3,        \"make\" : {          \"name\" : \"Audi\",          \"id\" : 3        }      }    },    \"client\" : {      \"name\" : \"Bogdan\",      \"id\" : 3    },    \"id\" : 4,    \"status\" : {      \"name\" : \"ACCEPTED\"    }  }, {    \"car\" : {      \"options\" : [ {        \"price\" : 65000,        \"name\" : \"Спортивный аэродинамический обвес\",        \"id\" : 3      }, {        \"price\" : 65000,        \"name\" : \"Спортивный аэродинамический обвес\",        \"id\" : 3      } ],      \"model\" : {        \"price\" : 6000000,        \"name\" : \"A8\",        \"id\" : 3,        \"make\" : {          \"name\" : \"Audi\",          \"id\" : 3        }      }    },    \"client\" : {      \"name\" : \"Bogdan\",      \"id\" : 3    },    \"id\" : 4,    \"status\" : {      \"name\" : \"ACCEPTED\"    }  } ]}");
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
